---
#this file will enable LLDP on the EdgeOS hosts specified then execute "show LLDP neighbors" and provide the output
- name: Enable LLDP and show lldp on EdgeOS hosts
  #connection: network_cli #define connection in inventory as "ansible_connection: network_cli"
  hosts: erx
  gather_facts: true

  tasks:
  - name: Show interfaces
    edgeos_command:
      commands: show interfaces
    register: if_output
  
  - name: display interfaces
    debug: var=if_output.stdout

  - name: enable VLANs on remote device
    edgeos_config:
      backup: yes
      comment: "adding trunk IFs"
      lines:
        - set interfaces ethernet {{trunk_int}} mtu 2018
        - set interfaces ethernet {{trunk_int}} vif {{vif1}} address {{vlan1_net}}{{svi}}/24
        - set interfaces ethernet {{trunk_int}} vif {{vif1}} mtu 2018
        - set interfaces ethernet {{trunk_int}} vif {{vif2}} address {{vlan2_net}}{{svi}}/24
        - set interfaces ethernet {{trunk_int}} vif {{vif2}} mtu 2018

  - name: Show interfaces
    edgeos_command:
      commands: show interfaces
    register: if_output
    
  - name: display interfaces
    debug: var=if_output.stdout