---
#ansible-playbook ~/edgeos-ansible/edgeos_banner_update.yaml -k -i joey-inventory.yaml
- name: Get output from devices
  hosts: erx
  gather_facts: true
  #connection: network_cli #define connection in inventory as "ansible_connection: network_cli"

  tasks:
  - name: Collect original banner config
    edgeos_command:
      commands: "show configuration commands | match banner"
    register: banner_old
#then come down below and use the below debug task to actually display the results
  - name: Display the old banner config
    debug: var=banner_old.stdout

  - name: Update banner to include hostname
    edgeos_config:
      backup: yes
      comment: "adding updated banner"
      lines: 
        - "{{ banner }}" #this is defined in the inventory file as

  - name: Collect new banner config
    edgeos_command:
      commands: "show configuration commands | match banner"
    register: banner_new
#then come down below and use the below debug task to actually display the results
  - name: Display the new banner config
    debug: var=banner_new.stdout