---
#ansible-playbook ~/edgeos-ansible/first_playbook.yaml -k -i ~/edgeos-ansible/yamsible-hosts.yaml
- name: Network Getting Started First Playbook

  #connection: network_cli move connection to inventory as "ansible_connection: network_cli"
#  ansible_network_os: edgeos
# ansible_user: ubnt
  hosts: erx
  tasks:

    - name: Get config for EdgeOS devices
      edgeos_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
